# Theme settings
dox:
    baseurl:
    title: r-pi
    theme_color: '#006699' # Define theme primary color with HEX value
    language: en-US # Use ISO language and country codes to setup language of your website - https://www.w3schools.com/tags/ref_language_codes.asp and https://www.w3schools.com/tags/ref_country_codes.asp
    header:
        logo:
            text: r-pi
            image:
        nav:
            - item_name: Homepage
              item_url: /
# Add top page menu items - add as many pages as needed
            - item_name: About
              item_url: /about
            - item_name: Emergency
              item_url: /blog
            - item_name: Photo
              item_url: /photo
        cta:
            label: Photo
            url: /photo
            icon: code # Choose from 266 icons in "Feather" icon set, list of all icons is available here - https://feathericons.com
        cta:
            label: Projects
            url: /projects
            icon: code # Choose from 266 icons in "Feather" icon set, list of all icons is available here - https://feathericons.com
    footer:
        logo:
            text: r-pi
            image:
        text: Copyright &copy; 2021. - r-pi <br>All rights reserved.
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: lls # Add your Disqus forum shortname to activate comments site-wide

# Defining collections
collections:
    documentation:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'documentation'
        values:
            layout: 'documentation-single'

# SASS settings
sass:
    sass_dir: ./dox-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./dox-theme/_layouts
includes_dir: ./dox-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/

# Google services
#google_analytics: UA-1349910-6

url: "https://mizuki.ch" # the base hostname & protocol for your site

plugins:
  - jekyll-sitemap
  - jekyll-analytics

# Photo gallery
#imagesurl: "/images/photo/"
thumbsurl: "/images/photo/thumbnail/"

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-1349910-6        # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

  Matomo:                   # Add, if you want to track with Matomo (former Piwik Analytics)
    url: stats.mizuki.ch    # Required - url to Matomo installation without trailing /
    siteId: "1"             # Required - replace with your Matomo site id (Write id as string)

